export const ADD_TO_CART = "ADD_TO_CART";
export const BUY_IT_NOW = "BUY_IT_NOW";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const RESET_CART = "RESET_CART";
export const INCREASE_QUALITY = "INCREASE_QUALITY";
export const DICREASE_QUALITY = "DICREASE_QUALITY";

